### ISSUE TITLE
how to export source point and dest point to a txt.

### ISSUE THREAD

**Issue by lanyanguang32** [snorpey/distort-grid#4]
how to export source point and dest point to a txt.

so can apply other distort image with like server image application.

thanks.

**Comment by snorpey** [comment]
hey @lanyanguang32, i think i could probably add that functionality. would it suffice to just export an array of point coordinates in JSON format? e.g: 

    [ {x: 23.3, y: 34.2 }, {x: 34.1, y: 64.2} ]

or would you need additional information?

**Comment by lanyanguang32** [comment]
@snorpey i would json format like   [{s:sx,sy,d:dx,dy},...]   [{s:"23.3,34.2",d:"34.1,64.2"},...]  think you.

**Comment by snorpey** [comment]
@lanyanguang32 i just added a button to download the data. the data format is slightly different to what you proposed: 

since there are two transforms for each tile (see https://github.com/snorpey/distort-grid/blob/develop/scripts/util/distort.js#L49-L124), one for the shape and one for the image, i added both, as well as the points.

i hope 

    [
      {
        "points": [ { "x": 0, "y": 0 }, { "x": 40, "y": 0 }, { "x": 0, "y": 40 }, { "x": 40, "y": 40 } ],
        "transforms": {
          "shape": {
            "scaleX": 1,
            "skewX": 0,
            "scaleY": 0,
            "skewY": 1,
            "translateX": 0,
            "translateY": 0
          },
          "image": {
            "scaleX": 1,
            "skewX": 0,
            "scaleY": 0,
            "skewY": 1,
            "translateX": 0,
            "translateY": 0
          }
        }
      }
    ]
