### ISSUE TITLE
Ask more explaination about this project

### ISSUE THREAD

**Issue by QiruiCao** [snorpey/distort-grid#6]
Hi, I found your project could really help out in my image processing work. But I'm not really familar with js. So could you please give more explainnation about how dose this front-end project work and the core logic in distort.js? Thanks a lot!

**Comment by snorpey** [comment]
hey @QiruiCao thank you for your interest in this project!

sorry for taking a while t^o answer your question. it's been some time since i wrote that code so i had to familiarize myself with it

 the core of the distort logic is using the native `setTransform()` `save()` and `clip()` methods of the [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D).

i learned a lot about how to do this kind of transformations from a [post in the "tecznotes" blog](http://mike.teczno.com/notes/canvas-warp.html) and one of the [code samples](https://s3.amazonaws.com/canvas-warp/2009-11-01/index.html) linked there.

please let me know if this explanation was sufficient (and i can close this issue) or if you need more information. thank you!
